services:
  app:
    build: .
    container_name: service
    command: npx nodemon --inspect=0.0.0.0:9000 -L src/index.js
    # command: npx nodemon --exec 'node --inspect=0.0.0.0:9000 --require ts-node/register src/index.ts'
    ports:
      - 5000:5000
      - 9000:9000
    volumes:
      - .:/usr/src/app
